# main.yml
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ virtual_network_name }}"
        address_prefixes: "{{ address_prefixes }}"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_address_prefix }}"
        virtual_network: "{{ virtual_network_name }}"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        name: "{{ public_ip_name }}"
      register: output_ip_address

    - name: Public IP of VM
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ security_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: "{{ ssh_source_ip }}"

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ network_interface_name }}"
        virtual_network: "{{ virtual_network_name }}"
        subnet: "{{ subnet_name }}"
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: "{{ public_ip_name }}"
        security_group: "{{ security_group_name }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/{{ admin_username }}/.ssh/authorized_keys
            key_data: "{{ ssh_key_data }}"
        network_interfaces: "{{ network_interface_name }}"
        managed_disk_type: "{{ managed_disk_type }}"
        image:
          offer: "{{ image_offer }}"
          publisher: "{{ image_publisher }}"
          sku: "{{ image_sku }}"
          version: "{{ image_version }}"
