# cleanup.yml
- name: Delete Azure resources
  hosts: localhost
  connection: local
  tasks:
    - name: Delete resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        state: absent
        force_delete_nonempty: true